println("🚀 AlphaFold3 Training Launcher")
println("Loading control script...")
include("run_modal_training.jl")
println()
println("=" ^ 80)
println("🧬 LAUNCHING FULL TRAINING PIPELINE ON MODAL.COM")
println("=" ^ 80)
println("  • 8x NVIDIA H100 GPUs")
println("  • Downloading all datasets to Modal")
println("  • Training AlphaFold3 with production data")
println("=" ^ 80)
println()
run_full_training_pipeline(epochs=100, batch_size=8, learning_rate=0.0001, download_data=true)
