println("=" ^ 80)
println("🧬 AlphaFold3 Modal.com Training - Quick Start")
println("=" ^ 80)
println()

modal_token_id = get(ENV, "MODAL_TOKEN_ID", "")
modal_token_secret = get(ENV, "MODAL_TOKEN_SECRET", "")

if isempty(modal_token_id) || isempty(modal_token_secret)
    println("❌ ERROR: Modal credentials not found!")
    println("Please set MODAL_TOKEN_ID and MODAL_TOKEN_SECRET in Replit Secrets")
    println()
    exit(1)
end

println("✅ Modal credentials configured")
println()
println("=" ^ 80)
println("🚀 TRAINING OPCIÓK")
println("=" ^ 80)
println()
println("1️⃣  TELJES PIPELINE (datasetek letöltése + training)")
println("    Automatikusan letölti az összes datasetet Modal-ra és elindítja a training-et")
println()
println("    julia> include(\"run_modal_training.jl\")")
println("    julia> run_full_training_pipeline(epochs=100, batch_size=8)")
println()
println("=" ^ 80)
println()
println("2️⃣  CSAK DATASETEK LETÖLTÉSE Modal-ra")
println("    Csak a dataseteket tölti le, training nélkül")
println()
println("    julia> include(\"run_modal_training.jl\")")
println("    julia> download_datasets_on_modal(\"all\")")
println()
println("=" ^ 80)
println()
println("3️⃣  CSAK TRAINING (datasetek már letöltve)")
println("    Ha a datasetek már letöltve vannak Modal-on")
println()
println("    julia> include(\"run_modal_training.jl\")")
println("    julia> run_full_training_pipeline(download_data=false)")
println()
println("=" ^ 80)
println()
println("4️⃣  CUSTOM PARAMÉTEREK")
println("    Saját beállításokkal")
println()
println("    julia> include(\"run_modal_training.jl\")")
println("    julia> run_full_training_pipeline(")
println("               epochs=200,")
println("               batch_size=16,")
println("               learning_rate=0.00005,")
println("               download_data=true")
println("           )")
println()
println("=" ^ 80)
println()
println("📊 KONFIGURÁCIÓ")
println("=" ^ 80)
println("  • GPU: 8x NVIDIA H100 (640GB VRAM összesen)")
println("  • CPU: 96 core")
println("  • RAM: 1TB")
println("  • Storage: Modal persistent volumes")
println("  • Datasetek: ~1TB (PDB, AlphaFold, UniProt, MGnify, EMPIAR, BMRB)")
println("  • Timeout: 7 nap")
println()
println("=" ^ 80)
println()
println("📖 RÉSZLETES DOKUMENTÁCIÓ")
println("=" ^ 80)
println("  Olvasd el: README_MODAL_TRAINING.md")
println()
println("=" ^ 80)
println()
println("✨ GYORS START - MOST INDÍTSD EL:")
println()
println("julia> include(\"run_modal_training.jl\")")
println("julia> run_full_training_pipeline()")
println()
println("=" ^ 80)
